CREATE TABLE IF NOT EXISTS imoveis (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  codigo VARCHAR(40) NOT NULL,
  titulo VARCHAR(220) NOT NULL,
  identificador VARCHAR(240) NOT NULL,
  descricao TEXT NULL,
  tipo VARCHAR(40) NOT NULL,
  subtipo VARCHAR(80) NULL,
  situacao VARCHAR(30) NOT NULL DEFAULT 'RASCUNHO',
  disponibilidade VARCHAR(30) NOT NULL DEFAULT 'DISPONIVEL',
  lancamento_id BIGINT UNSIGNED NULL,
  valor_venda DECIMAL(14, 2) NULL,
  valor_condominio DECIMAL(12, 2) NULL,
  valor_iptu DECIMAL(12, 2) NULL,
  periodicidade_iptu VARCHAR(10) NULL,
  valor_outras_despesas DECIMAL(12, 2) NULL,
  aceita_financiamento TINYINT(1) NULL,
  aceita_permuta TINYINT(1) NULL,
  area_total DECIMAL(10, 2) NULL,
  area_util DECIMAL(10, 2) NULL,
  area_construida DECIMAL(10, 2) NULL,
  unidade_area_total VARCHAR(12) NULL DEFAULT 'M2',
  frente_terreno DECIMAL(10, 2) NULL,
  fundos_terreno DECIMAL(10, 2) NULL,
  topografia VARCHAR(30) NULL,
  quartos SMALLINT UNSIGNED NULL,
  suites SMALLINT UNSIGNED NULL,
  banheiros SMALLINT UNSIGNED NULL,
  vagas SMALLINT UNSIGNED NULL,
  andar SMALLINT UNSIGNED NULL,
  unidade VARCHAR(30) NULL,
  total_andares SMALLINT UNSIGNED NULL,
  elevador TINYINT(1) NULL,
  pe_direito DECIMAL(8, 2) NULL,
  cep VARCHAR(10) NULL,
  estado CHAR(2) NULL,
  cidade VARCHAR(160) NULL,
  bairro VARCHAR(160) NULL,
  logradouro VARCHAR(220) NULL,
  numero VARCHAR(30) NULL,
  complemento VARCHAR(120) NULL,
  nome_condominio VARCHAR(180) NULL,
  ponto_referencia VARCHAR(180) NULL,
  exibir_endereco_exato TINYINT(1) NOT NULL DEFAULT 0,
  destaque TINYINT(1) NOT NULL DEFAULT 0,
  publicado_em DATETIME NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY imoveis_codigo (codigo),
  UNIQUE KEY imoveis_identificador (identificador),
  INDEX imoveis_publicos (situacao, disponibilidade, tipo),
  INDEX imoveis_localizacao (cidade, bairro)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
