CREATE TABLE IF NOT EXISTS midias (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  imovel_id BIGINT UNSIGNED NOT NULL,
  tipo VARCHAR(20) NOT NULL DEFAULT 'IMAGEM',
  arquivo VARCHAR(500) NOT NULL,
  largura INT UNSIGNED NULL,
  altura INT UNSIGNED NULL,
  descricao VARCHAR(300) NULL,
  ordem SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  principal TINYINT(1) NOT NULL DEFAULT 0,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX midias_por_imovel (imovel_id, ordem),
  CONSTRAINT midias_imovel_fk FOREIGN KEY (imovel_id)
    REFERENCES imoveis (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
