CREATE TABLE IF NOT EXISTS configuracao_manutencao (
  id TINYINT UNSIGNED NOT NULL,
  ativa TINYINT(1) NOT NULL DEFAULT 0,
  atualizada_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO configuracao_manutencao (id, ativa)
VALUES (1, 0)
ON DUPLICATE KEY UPDATE id = id;
