import type { Empreendimento } from "@/tipos/imovel";

export const empreendimentos: Empreendimento[] = [
  {
    id: "e1",
    slug: "unique-palestra",
    nome: "Unique Palestra",
    tipo: "apartamento",
    cidade: "São José do Rio Preto",
    bairro: "Região Oeste",
    estado: "SP",
    precoApartir: 147840,
    area: 41.5,
    quartos: 2,
    detalhesExtras: ["Entrada facilitada"],
    mcmv: true,
    descricao:
      "Empreendimento residencial na região oeste de São José do Rio Preto, com unidades a partir de 41,5 m² e duas dormitórios. Opção alinhada ao programa Minha Casa Minha Vida.",
    caracteristicas: ["2 dormitórios", "41,5 m²", "MCMV"],
    fotos: [],
  },
  {
    id: "e2",
    slug: "palestra-life",
    nome: "Palestra Life",
    tipo: "apartamento",
    cidade: "São José do Rio Preto",
    bairro: "Região Oeste",
    estado: "SP",
    precoApartir: 187920,
    area: 45,
    quartos: 2,
    mcmv: true,
    descricao:
      "Apartamentos na região oeste de Rio Preto, com tipologias a partir de 45 m². Ideal para quem busca lançamento com condições de financiamento.",
    caracteristicas: ["2 dormitórios", "45 m²", "Lançamento"],
    fotos: [],
  },
  {
    id: "e3",
    slug: "trend-residence",
    nome: "Trend Residence",
    tipo: "apartamento",
    cidade: "São José do Rio Preto",
    bairro: "Região Norte",
    estado: "SP",
    precoApartir: 210000,
    area: 48,
    quartos: 2,
    mcmv: true,
    descricao:
      "Residencial na região norte de São José do Rio Preto, com apartamentos a partir de R$ 210.000.",
    caracteristicas: ["2 dormitórios", "48 m²"],
    fotos: [],
  },
  {
    id: "e4",
    slug: "vila-harmonia",
    nome: "Vila Harmonia",
    tipo: "casa",
    cidade: "São José do Rio Preto",
    bairro: "Região Norte",
    estado: "SP",
    precoApartir: 208000,
    area: 55,
    quartos: 2,
    mcmv: true,
    descricao:
      "Casas na região norte de Rio Preto, com tipologias a partir de 55 m².",
    caracteristicas: ["Casa", "2 dormitórios", "55 m²"],
    fotos: [],
  },
  {
    id: "e5",
    slug: "ecoviva-mais-parque",
    nome: "Ecoviva Mais Parque",
    tipo: "apartamento",
    cidade: "São José do Rio Preto",
    bairro: "Região Leste",
    estado: "SP",
    precoApartir: 170000,
    area: 42,
    quartos: 2,
    mcmv: true,
    descricao:
      "Empreendimento na região leste de São José do Rio Preto, com unidades a partir de R$ 170.000.",
    caracteristicas: ["2 dormitórios", "42 m²"],
    fotos: [],
  },
  {
    id: "e6",
    slug: "residencial-piavon",
    nome: "Residencial Piavon",
    tipo: "apartamento",
    cidade: "São José do Rio Preto",
    bairro: "Região Norte",
    estado: "SP",
    precoApartir: 147000,
    area: 44,
    quartos: 2,
    detalhesExtras: ["Entrada até 180x"],
    mcmv: true,
    descricao:
      "Residencial na região norte de Rio Preto, com entrada parcelada e tipologias compactas de dois dormitórios.",
    caracteristicas: ["2 dormitórios", "44 m²", "Entrada parcelada"],
    fotos: [],
  },
  {
    id: "e7",
    slug: "clarice-novelli",
    nome: "Clarice Novelli",
    tipo: "casa",
    cidade: "São José do Rio Preto",
    bairro: "Região Sul",
    estado: "SP",
    precoApartir: 174250,
    area: 43.85,
    quartos: 2,
    entrega: "mar/2028",
    mcmv: true,
    descricao:
      "Casas na região sul de São José do Rio Preto, com entrega prevista para março de 2028.",
    caracteristicas: ["Casa", "2 dormitórios", "43,85 m²"],
    fotos: [],
  },
  {
    id: "e8",
    slug: "moravida-sao-bento",
    nome: "Moravida São Bento",
    tipo: "casa",
    cidade: "São José do Rio Preto",
    bairro: "Shopping Norte",
    estado: "SP",
    precoApartir: 185000,
    area: 46.53,
    quartos: 2,
    entrega: "jan/2028",
    mcmv: true,
    descricao:
      "Casas próximas à região do Shopping Norte, com tipologias a partir de 46,53 m².",
    caracteristicas: ["Casa", "2 dormitórios", "46,53 m²"],
    fotos: [],
  },
  {
    id: "e9",
    slug: "flor-do-campo",
    nome: "Flor do Campo",
    tipo: "casa",
    cidade: "Mirassol",
    bairro: "Mirassol",
    estado: "SP",
    precoApartir: 164000,
    area: 41.9,
    quartos: 2,
    entrega: "mar/2028",
    mcmv: true,
    descricao:
      "Casas em Mirassol, com tipologias a partir de 41,9 m² e entrega prevista para março de 2028.",
    caracteristicas: ["Casa", "2 dormitórios", "41,9 m²"],
    fotos: [],
  },
  {
    id: "e10",
    slug: "villa-do-sol",
    nome: "Villa do Sol",
    tipo: "apartamento",
    cidade: "Mirassol",
    bairro: "Centro",
    estado: "SP",
    precoApartir: 155000,
    area: 40.44,
    quartos: 2,
    detalhesExtras: ["Entrada até 100x"],
    mcmv: true,
    descricao:
      "Apartamentos no centro de Mirassol, com unidades a partir de 40,44 m² e entrada parcelada.",
    caracteristicas: ["2 dormitórios", "40,44 m²", "Centro"],
    fotos: [],
  },
  {
    id: "e11",
    slug: "aurora-3",
    nome: "Aurora 3",
    tipo: "casa",
    cidade: "Bady Bassitt",
    bairro: "Bady Bassitt",
    estado: "SP",
    precoApartir: 145000,
    area: 43.77,
    quartos: 2,
    entrega: "out/2027",
    mcmv: true,
    descricao:
      "Casas em Bady Bassitt, com tipologias a partir de 43,77 m² e entrega prevista para outubro de 2027.",
    caracteristicas: ["Casa", "2 dormitórios", "43,77 m²"],
    fotos: [],
  },
  {
    id: "e12",
    slug: "bosque-lago-sul",
    nome: "Bosque Lago Sul",
    tipo: "casa",
    cidade: "Bady Bassitt",
    bairro: "Bady Bassitt",
    estado: "SP",
    precoApartir: 230500,
    area: 58.15,
    quartos: 2,
    entrega: "mar/2028",
    detalhesExtras: ["Faixa 3"],
    mcmv: true,
    descricao:
      "Casas em Bady Bassitt compatíveis com Faixa 3 do Minha Casa Minha Vida, com tipologias a partir de 58,15 m².",
    caracteristicas: ["Casa", "Faixa 3", "58,15 m²"],
    fotos: [],
  },
];

export function obterEmpreendimentoPorSlug(
  slug: string
): Empreendimento | undefined {
  return empreendimentos.find((item) => item.slug === slug);
}
